# -*- coding: utf-8 -*-
"""Sales forecasting analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EnwhuaDb8nVVuBvgIddfdEQkq9_yzLkg

Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

"""Load Dataset"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

print(df.head())
print(df.info())

"""Data Cleaning and preprocessing"""

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
print(df.isnull().sum())
df = df.drop_duplicates()
df = df.sort_values(by='Order Date')

print("Cleaned Data Shape:", df.shape)

"""Descriptive Statistics"""

print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Maximum Sales:", df['Sales'].max())
print("Minimum Sales:", df['Sales'].min())

print(df.describe())

"""Sales Trend Analysis (Time Series)"""

daily_sales = df.groupby('Order Date')['Sales'].sum()

plt.figure(figsize=(12,5))
plt.plot(daily_sales)
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

"""Monthly & Yearly Analysis"""

df['year'] = df['Order Date'].dt.year
df['month'] = df['Order Date'].dt.month

monthly_sales = df.groupby('month')['Sales'].sum()

plt.figure(figsize=(8,5))
monthly_sales.plot(kind='bar')
plt.title("Monthly Sales")
plt.show()

yearly_sales = df.groupby('year')['Sales'].sum()

plt.figure(figsize=(8,5))
yearly_sales.plot(kind='bar')
plt.title("Yearly Sales")
plt.show()

"""Store Analysis"""

store_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(10,5))
store_sales.plot(kind='bar')
plt.title("Sales by Category")
plt.show()

"""Product (Item) Analysis"""

item_sales = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False)

top_items = item_sales.head(10)

plt.figure(figsize=(10,5))
top_items.plot(kind='bar')
plt.title("Top 10 Best-Selling Products")
plt.show()

"""Sales Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'], bins=50)
plt.title("Sales Distribution")
plt.show()

"""Box Plot"""

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Sales'])
plt.title("Sales Outliers")
plt.show()

"""Relationship Analysis"""

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""Simple Forecasting"""

daily_sales_ma = daily_sales.rolling(window=7).mean()

plt.figure(figsize=(12,5))
plt.plot(daily_sales, label='Actual Sales')
plt.plot(daily_sales_ma, label='7-Day Moving Avg')
plt.legend()
plt.title("Sales Forecast Trend (Simple)")
plt.show()

"""Business Insights"""

print("Top Store:", store_sales.idxmax())
print("Top Product:", item_sales.idxmax())

print("Peak Sales Month:", monthly_sales.idxmax())
print("Lowest Sales Month:", monthly_sales.idxmin())